import type { Metadata } from "next";
import "./globals.css";
import { FiraCode, Quantico, Inter } from "@/fonts/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.variable} ${Quantico.variable} ${FiraCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
